### ISSUE TITLE
TypeError when using  Orderable on regular Django models.Model

### ISSUE THREAD

**Issue by wytsekamsma** [elton2048/wagtail-orderable#7] opened 2019-04-05 09:28 UTC
I'm running into a TypeError concerning MRO when combining the Orderable Class with a regular Django Model (as shown in the readme). 

```
[...]
File "/var/www/ska/wagtail_orderable_test/models.py", line 5, in <module>
    class YourModel(models.Model, Orderable):
  File "/var/www/ska/studioska/lib/python3.6/site-packages/django/db/models/base.py", line 94, in __new__
    new_class = super_new(cls, name, bases, new_attrs, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Model, Orderable
```

This is using the exact example as shown in the readme:

```
from django.db import models

from wagtailorderable.models import Orderable

class YourModel(models.Model, Orderable):
    title = models.CharField(max_length=200)
```

The example using the Page class from Wagtail does work. As far as I can gather (with somewhat limited knowledge concerning subclassing in Python) this error is concerning the concatenation of class-methods, although I'm not able to determine where exactly this problem originates.

It is quite possible this is user-error (as mentioned, I'm not a python expert). 

For reference, I'm using Wagtail 2.4 (latest stable) with Django 2.1.8 (latest version indicated for Wagtail 2.4) and Python 3.6.7.

**Comment by benoitvogel** [comment] 2019-04-06 03:12
Seems to be working when switching the order of the parent classes. Try:
```
class YourModel(Orderable, models.Model):
```

**Comment by wytsekamsma** [comment] 2019-04-08 08:43
That does the trick! Strange, I thought I had already tried that, but guess not. 
One caveat: I had to define list_display (in the admin declaration) as a list. Apparently by default this is a tuple which doesn't concatenate with the list_display the OrderableMixin tries to add.

models.py:
```
[...]
class YourModel(Orderable, models.Model):
    title = models.CharField(max_length=200)

```
wagtail_hooks.py:
```
[...]
class YourModelAdmin(OrderableMixin, ModelAdmin):
    model = YourModel
    list_display =['__str__']
    ordering = ('sort_order',)    
[...]
```

Maybe this could be updated in the example in the readme? I'll leave this open for consideration.

Thanks!

**Comment by benoitvogel** [comment] 2019-04-08 13:56
Same thing here, made a PR for this : #8

**Comment by elton2048** [comment] 2019-05-31 03:56
I have merged #8 to handle `list_display` with tuple, I am pleased if someone checks whether it is still required to define `list_display` in corresponds ModelAdmin in order to work.

**Comment by benoitvogel** [comment] 2019-06-02 21:54
Thanks for your comment. I don't have much time right now to check thoroughly but after fixing the SyntaxError from PR #15 it seems to be fine. If I comment `list_display` on my project it displays 1 column for ordering + 1 column populated with __str__() for every instance of the model.

**Comment by dcentrica** [comment] 2020-09-01 02:12
@elton2048 I can confirm that in Wagtail 2.8.1, omitting / removing / commenting `list_display` in a `ModelAdmin` makes no difference to the drag / drop functionality. It works without. I think it depends on if you've declared `__str__()` on your model or not.

**Comment by elton2048** [comment] 2022-06-18 15:59
Seems no issue on that already. Please open a new issue if you faced same issue again

**Closed as completed by elton2048** 2022-06-18 15:59 UTC
